sudo: required

services:
  - docker

before_install:
  - docker info

install:
  - docker build -t nktpro/reack .

script:
  - docker run -i -v ${PWD}/test:/opt/reack/app -w /opt/reack/app nktpro/reack gulp
  - ls ${PWD}/test/build/index.js && ls ${PWD}/test/build/index.html

before_deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  
deploy:
  - docker push nktpro/reack
